language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2/repository"
#after_success:
#  - mvn clean coveralls:report
before_install:
  - chmod +x mvnw
after_success:
  - bash <(curl -s https://codecov.io/bash)